# Generated by Django 6.0.2 on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0002_alter_service_options_service_benefit_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Service",
            new_name="SalonService",
        ),
        migrations.RenameField(
            model_name="salonservice",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterModelOptions(
            name="salonservice",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="salonservice",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="salonservice",
            name="duration",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="salonservice",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="currency",
            field=models.CharField(default="AED", max_length=10),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="booking_source",
            field=models.CharField(default="Website + WhatsApp", max_length=100),
        ),
        migrations.RemoveField(
            model_name="salonservice",
            name="category",
        ),
        migrations.RemoveField(
            model_name="salonservice",
            name="benefit",
        ),
        migrations.RemoveField(
            model_name="salonservice",
            name="features",
        ),
        migrations.RemoveField(
            model_name="salonservice",
            name="popular",
        ),
        migrations.RemoveField(
            model_name="salonservice",
            name="sort_order",
        ),
        migrations.RemoveField(
            model_name="salonservice",
            name="image",
        ),
        migrations.RemoveField(
            model_name="salonservice",
            name="image_alt",
        ),
    ]
