# Generated by Django 6.0.2 on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0003_rename_service_to_salonservice_and_rework_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="salonservice",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
    ]
